### ISSUE TITLE
boost::asio server_zone crash

### ISSUE THREAD

**Issue by AcedArmy** [SapphireMordred/Sapphire#24]
Happens when sending something in chat and or handling the packet : DiscoveryHandler While outbound/external connection

Call Stack: https://pastebin.com/h5JSVHcQ
Dump: [server_zone.zip](https://github.com/SapphireMordred/Sapphire/files/1214377/server_zone.zip)

**Comment by SapphireMordred** [comment]
First impression is that this happens cause of fragmented packets, in fact any packet that isn't delivered in one shot or even invalid packets can and likely will crash the server. Need further investigation.
Ideally a wireshark capture of the packets sent / received when the crash happens.

**Comment by SapphireMordred** [comment]
The same crash occurs when the server receives any invalid packet. We need extra checks to make sure the packet we receive has a valid ffxiv header.

**Comment by Minoost** [comment]
## Tasks
- [ ] Proper tcp packet segmentation handling (Queue bytes)
- [ ] Drop connection if ```FFXIVARR_PACKET_HEADER``` (IPC Message container) is abnormally large.
- [ ] Drop connection if reported size of ```FFXIVARR_PACKET_RAW``` (Ipc message itself) is abnoramlly large.
- [ ] Check ```sizeof(EXPECTED_SIZE_FOR_SPECIFIC_OPCODE) <= sizeof(ACTUAL_SIZE)``` before reading. (Atleast it should handle that ```&m_dataBuf[0] + pos``` should NOT point out of received buffer )
